### ISSUE TITLE
Serializes Date by its julianNumber. The deserialization creates a Date with duration 0, instead of 1 as expected

### ISSUE THREAD

**Issue by StephanEggermont** [pharo-nosql/OmniBase#5]

**Comment by StephanEggermont** [comment]
Added the offset. Only works for whole hours, https://github.com/StephanEggermont/OmniBase/commit/a124d78636150416422d697f3c75213c74049d29

**Comment by noha** [comment]
If you are willing to provide a fix reopen otherwise this stays closed
